# Generated by Django 5.1.4 on 2024-12-22 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c3_crawling_app', '0002_alter_ranking_brand_alter_ranking_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranking',
            name='brand',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='cosmetic_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='cosmetic_url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='image_url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='oy_price',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='price',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='zz_price',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterModelTable(
            name='ranking',
            table='ranking',
        ),
    ]
